import pandas as pd


def replace_norwegian_characters(string):
    char_dict = {'æ': 'ae', 'Æ': 'Ae', 'ø': 'o', 'Ø':'O', 'å':'aa', 'Å':'Aa'}
    for char, replacement in char_dict.items():
        string = string.replace(char, replacement)
    return string


def map_fish():    
    # Fresh water
    df_fresh = pd.read_excel('data/Arter.xlsx', sheet_name='Ferskvann')
    artsnavn_fresh = df_fresh['Art'].map(lambda x: replace_norwegian_characters(x))
    artsnavn_fresh = artsnavn_fresh.sort_values()
    n_fresh = len(artsnavn_fresh)
    
    for i, fish in enumerate(artsnavn_fresh):    
        print("'%s': %i," % (fish, i))
    
    # Salt water
    df_salt = pd.read_excel('data/Arter.xlsx', sheet_name='Saltvann')
    artsnavn_salt = df_salt['Art'].map(lambda x: replace_norwegian_characters(x))
    artsnavn_salt = artsnavn_salt.sort_values()    
    
    for i, fish in enumerate(artsnavn_salt):    
        print("'%s': %i," % (fish, i+n_fresh))



def fish_to_num_mapping():
    """
    Create mapping from fish name to number
    """
    fish_dict = {
        'Aal': 0,
        'Abbor': 1,
        'Asp': 2,
        'Bekkeroye': 3,
        'Brasme': 4,
        'Canadaroye': 5,
        'Dvergmalle': 6,
        'Flire': 7,
        'Gjedde': 8,
        'Gjors': 9,
        'Gullbust': 10,
        'Gullfisk': 11,
        'Harr': 12,
        'Hork': 13,
        'Hornulke': 14,
        'Hvitfinnet steinulke': 15,
        'Karpe': 16,
        'Karuss': 17,
        'Ketalaks': 18,
        'Krokle': 19,
        'Lagesild': 20,
        'Lake': 21,
        'Laks': 22,
        'Laue': 23,
        'Maisild': 24,
        'Mort': 25,
        'Nipigget stingsild': 26,
        'Orekyt': 27,
        'Orret': 28,
        'Pukkellaks': 29,
        'Regnbueorret': 30,
        'Regnlaue': 31,
        'Rodgjellet solabbor': 32,
        'Roye': 33,
        'Sandkryper (grundling)': 34,
        'Sik': 35,
        'Sorv': 36,
        'Stam': 37,
        'Stamsild': 38,
        'Steinsmett': 39,
        'Suter': 40,
        'Trepigget stingsild': 41,
        'Vederbuk': 42,
        'Aalekvabbe': 43,
        'Arktisk knurrulke': 44,
        'Auxid': 45,
        'Berggylt': 46,
        'Bergkutling': 47,
        'Bergnebb': 48,
        'Berlevaagfisk': 49,
        'Blaahai': 50,
        'Blaakjeft': 51,
        'Blaakveite': 52,
        'Blaalange': 53,
        'Blaastaal': 54,
        'Blaasteinbit': 55,
        'Breiflabb': 56,
        'Brisling': 57,
        'Brosme': 58,
        'Brungylt': 59,
        'Dvergulke': 60,
        'Femtraadet tangbrosme': 61,
        'Firetraadet tangbrosme': 62,
        'Fjesing': 63,
        'Flekket floyfisk': 64,
        'Flekksteinbit': 65,
        'Gapeflyndre': 66,
        'Glasskutling': 67,
        'Glasstunge': 68,
        'Glassvar': 69,
        'Glattulke': 70,
        'Graahai': 71,
        'Graasteinbit': 72,
        'Gressgylt': 73,
        'Gronngylt': 74,
        'Haabrann': 75,
        'Haagjel': 76,
        'Haakjerring': 77,
        'Haarvar': 78,
        'Havaal': 79,
        'Havabbor': 80,
        'Havbrasme': 81,
        'Havmus': 82,
        'Havsil': 83,
        'Horngjel': 84,
        'Hornkvabbe': 85,
        'Hvitskate': 86,
        'Hvitting': 87,
        'Hyse': 88,
        'Isgalt': 89,
        'Isskate': 90,
        'Kloskate': 91,
        'Kolmule': 92,
        'Krokulke': 93,
        'Krumsnutet havnaal': 94,
        'Krystallkutling': 95,
        'Kveite': 96,
        'Lange': 97,
        'Langhalet langebarn': 98,
        'Leirkutling': 99,
        'Liten floyfisk': 100,
        'Liten havnaal': 101,
        'Liten kantnaal': 102,
        'Lodde': 103,
        'Lomre': 104,
        'Lusuer': 105,
        'Lyr': 106,
        'Lysing': 107,
        'Makrell': 108,
        'Makrellhai': 109,
        'Makrellstorje': 110,
        'Marmorert berguer': 111,
        'Mora': 112,
        'Mudderkutling': 113,
        'Mulle': 114,
        'Nebbskate': 115,
        'Nordlig aalebrosme': 116,
        'Nordlig knurrulke': 117,
        'Nordlig tangbrosme': 118,
        'Oyepaal': 119,
        'Paddetorsk': 120,
        'Panserulke': 121,
        'Pigghaa': 122,
        'Piggkutling': 123,
        'Piggskate': 124,
        'Piggulke': 125,
        'Piggvar': 126,
        'Polartorsk': 127,
        'Rodflekket kutling': 128,
        'Rodknurr': 129,
        'Rodspette': 130,
        'Rundskate': 131,
        'Sandflyndre': 132,
        'Sandkutling': 133,
        'Sandskate': 134,
        'Sardin': 135,
        'Sei': 136,
        'Sild': 137,
        'Skjeggtorsk': 138,
        'Skjellbrosme': 139,
        'Skolest': 140,
        'Skrubbe': 141,
        'Slettvar': 142,
        'Smaaflekket rodhai': 143,
        'Smaasil': 144,
        'Smaavar': 145,
        'Smorflyndre': 146,
        'Snabeluer': 147,
        'Solvbrasme': 148,
        'Solvkveite': 149,
        'Solvtangbrosme': 150,
        'Solvtorsk': 151,
        'Spisshalet kutling': 152,
        'Spisskate': 153,
        'St.Peterfisk': 154,
        'Stor havnaal': 155,
        'Stor kantnaal': 156,
        'Storflekket rodhai': 157,
        'Storsil': 158,
        'Storskate': 159,
        'Strandtangbrosme': 160,
        'Stripet pelamide': 161,
        'Stromsild': 162,
        'Svarthaa': 163,
        'Svartkutling': 164,
        'Svartskate': 165,
        'Sypike': 166,
        'Taggmakrell': 167,
        'Tangkutling': 168,
        'Tangkvabbe': 169,
        'Tangsnelle': 170,
        'Tangsprell': 171,
        'Tangstikling': 172,
        'Tiskjegg': 173,
        'Torsk': 174,
        'Torulke': 175,
        'Tretraadet tangbrosme': 176,
        'Tunge': 177,
        'Tungevar': 178,
        'Tverrhalet langebarn': 179,
        'Tykkleppet multe': 180,
        'Uer': 181,
        'Ulkekutling': 182,
        'Vanlig aalebrosme': 183,
        'Vanlig floyfisk': 184,
        'Vanlig knurr': 185,
        'Vanlig rognkjeks': 186,
        'Vanlig ulke': 187,
        'Vassild': 188,
        'Vortekjeks': 189
    }

    return fish_dict